#!/usr/bin/env bash
set -e

## Install the libsasl Libraries
cd opt/
wget 'https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-2.1.28/cyrus-sasl-2.1.28.tar.gz'
tar -xf cyrus-sasl-2.1.28.tar.gz
cd cyrus-sasl-2.1.28
./configure
make
make install
ln -s /usr/local/lib/sasl2 /usr/lib/sasl2

## Installing the Connector on Debian
wget 'https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/odbc/2.6.26/SimbaSparkODBC-2.6.26.1045-Debian-64bit.zip'
unzip SimbaSparkODBC-2.6.26.1045-Debian-64bit.zip
dpkg -i simbaspark_2.6.26.1045-2_amd64.deb

echo '[ODBC Data Sources]
Databricks=Databricks ODBC Connector
[Databricks]
Driver=/opt/simba/spark/lib/64/libsparkodbc_sb64.so' > /etc/odbc.ini